# Generated by Django 5.2.3 on 2025-07-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_data',
            new_name='User_Tasks',
        ),
    ]
